# Catppuccin Mocha Theme for Yazi

[manager]
cwd = { fg = "#cdd6f4" }

# Hovered
hovered         = { fg = "#1e1e2e", bg = "#89b4fa" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#f9e2af", italic = true }
find_position = { fg = "#f38ba8", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_copied   = { fg = "#f9e2af", bg = "#f9e2af" }
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" }

# Tab
tab_active   = { fg = "#1e1e2e", bg = "#cdd6f4" }
tab_inactive = { fg = "#cdd6f4", bg = "#313244" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#585b70" }

# Highlighting
syntect_theme = "~/.config/bat/themes/Catppuccin Mocha.tmTheme"

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#585b70", bg = "#585b70" }

# Mode
mode_normal = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
mode_select = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
mode_unset  = { fg = "#1e1e2e", bg = "#f38ba8", bold = true }

# Progress
progress_label  = { fg = "#cdd6f4", bold = true }
progress_normal = { fg = "#89b4fa", bg = "#313244" }
progress_error  = { fg = "#f38ba8", bg = "#313244" }

# Permissions
permissions_t = { fg = "#89b4fa" }
permissions_r = { fg = "#f9e2af" }
permissions_w = { fg = "#f38ba8" }
permissions_x = { fg = "#a6e3a1" }
permissions_s = { fg = "#585b70" }

[input]
border   = { fg = "#89b4fa" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#89b4fa" }
active   = { fg = "#f9e2af" }
inactive = {}

[tasks]
border  = { fg = "#89b4fa" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#313244" }
cand            = { fg = "#89b4fa" }
rest            = { fg = "#585b70" }
desc            = { fg = "#f9e2af" }
separator       = " ➜ "
separator_style = { fg = "#585b70" }

[help]
on      = { fg = "#a6e3a1" }
exec    = { fg = "#89b4fa" }
desc    = { fg = "#585b70" }
hovered = { bg = "#313244", bold = true }
footer  = { fg = "#cdd6f4", bg = "#313244" }
